import pyautogui as gui

#gui.displayMousePosition()#35 183/ 402 126

gui.click(35, 183, duration=0.5)
gui.click(390, 126, duration=0.5)
gui.write('TestBot.py', interval=0.1)
gui.click(35, 183, duration=0.5)

gui.sleep(0.2)
gui.write('i = 1')
gui.hotkey('enter')
gui.write('while i < 10:')
gui.hotkey('enter')
gui.write('i += 1')
gui.hotkey('enter')
gui.write('import pyautogui as gui')
gui.hotkey('enter')
gui.write("gui.hotkey('enter')")
gui.hotkey('enter')
gui.write("gui.click(35, 183, duration=0.5)", interval=0.01)
gui.hotkey('enter')
gui.write("gui.hotkey('enter')")
gui.hotkey('enter')
gui.write("gui.click(390, 126, duration=0.5)", interval=0.01)
gui.hotkey('enter')
gui.write("gui.hotkey('enter')")
gui.hotkey('enter')
gui.write("gui.write(f\'TestBot{i}.py\', interval=0.01)", interval=0.01)
gui.hotkey('enter')
gui.write("gui.hotkey('enter')")
gui.hotkey('enter')
gui.write("gui.click(35, 183, duration=0.5)", interval=0.01)
gui.hotkey('enter')
gui.write("gui.write('print(\"Hello World\")')", interval=0.01)
gui.hotkey('enter')
gui.write('gui.click(1773,  84, duration=0.5)')
gui.hotkey('enter')
gui.write("gui.hotkey('enter')")
gui.hotkey('enter')
print("Hello World")

gui.leftClick(1773,  84, duration=1)