import pyautogui as gui

validaçao = ['if','else','elif','match','case','try','except']
rept = ['while','for']

gui.click(35, 183, duration=0.5)
gui.click(350, 126, duration=0.5)
gui.write('Uff.py', interval=0.1)
gui.click(35, 183, duration=0.5)
gui.moveTo(350, 80,duration=0.5)

gui.sleep(0.5)
gui.write('i = 1', interval=0.05)
gui.hotkey('enter')
gui.write('n = []', interval=0.05)
gui.hotkey('enter')
gui.write(f'{rept[0]} i < 6:', interval=0.05)
gui.hotkey('enter')
gui.write(f'{validaçao[5]}:', interval=0.05)
gui.hotkey('enter')
gui.write('n.append(float(input(f"Ad {i}:")))', interval=0.05)
gui.hotkey('enter')
gui.write('i += 1', interval=0.05)
gui.hotkey('enter')
gui.hotkey('backspace')
gui.write(f'{validaçao[6]}:', interval=0.05)
gui.hotkey('enter')
gui.write('print("Erro")', interval=0.05)
gui.hotkey('enter')
gui.hotkey('backspace')
gui.hotkey('backspace')
gui.write('print(sum(n))', interval=0.05)
gui.hotkey('enter')
gui.click(1773,  84, duration=0.5)
gui.sleep(2)
gui.click(1000,  900, duration=0.5)

gui.write('1', interval=0.05)
gui.hotkey('enter')
gui.write('1', interval=0.05)
gui.hotkey('enter')
gui.write('1', interval=0.05)
gui.hotkey('enter')
gui.write('1', interval=0.05)
gui.hotkey('enter')
gui.write('1', interval=0.05)
gui.hotkey('enter')